name: QReward CI
on: [push, pull_request]

jobs:
  lint:
    name: "Lint QReward"
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    runs-on: ${{ github.repository == 'AQ-MedAI/QReward' || matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Run lints
        run: |
          make lint

  test:
    name: "Test QReward"

    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Run unit test
        run: |
          pip install .
          make test
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.python-version }}
          path: cobertura.xml

  codecov:
    name: "Upload coverage"
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: coverage-files
      - run: ls coverage-files

      - name: Upload to Codecov
        run: |
          codecov -f coverage-files/**/*.xml
